server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
  gateway:
    address: http://kong.test.svc.cluster.local:8001
  cluster:
    namespace: test
  compilationCenter:
    address: compilation-center.test.svc.cluster.local:9000
  appDomainName: kong.test.svc.cluster.local
  influxdb:
    serverUrl: http://influxdb.test.svc.cluster.local:8086
    authToken: test
    org: test
data:
  redis:
    host: test-redis.test.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
