server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
    port: 8000
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
  gateway:
    address: http://kong.test.svc.cluster.local:8001
    routeTimeout: 20s
service:
  codeGenerator:
    dataCollectionTmplRoot: data-colletion-template
    dataProcessingTmplRoot: data-processing-template
data:
  redis:
    host: test-redis.test.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
