server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
  gateway:
    address: http://kong.test.svc.cluster.local:8001
  cluster:
    namespace: test
  appDomainName: gd-k8s-master01
service:
  codeGenerator:
    dataCollectionTmplRoot: /app/service-centre/internal/biz/codegenerator/data-processing-template
    dataProcessingTmplRoot: /app/service-centre/internal/biz/codegenerator/data-processing-template
data:
  redis:
    host: test-redis.test.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
