// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/moyusir/service-centre/internal/biz"
	"gitee.com/moyusir/service-centre/internal/conf"
	"gitee.com/moyusir/service-centre/internal/data"
	"gitee.com/moyusir/service-centre/internal/server"
	"gitee.com/moyusir/service-centre/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confService *conf.Service, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewRedisRepo(dataData, logger)
	userUsecase, err := biz.NewUserUsecase(confServer, confService, userRepo, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(userUsecase)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
